plugins {
    id 'com.android.application'
}

android {
    namespace 'com.kenzelyom.walletlistener'
    compileSdk 35

    defaultConfig {
        applicationId "com.kenzelyom.walletlistener"
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName "1.0.0"
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            minifyEnabled false
            shrinkResources false
        }
    }
}
